./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 1 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_1 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 2 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_2 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 3 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_3 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 4 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_4 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 5 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_5 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 6 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_6 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 7 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_7 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 8 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_8 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 9 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_9 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 10 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_10 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 11 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_11 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 12 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_12 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 13 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_13 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 14 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_14 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 15 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_15 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 16 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_16 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 17 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_17 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 18 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_18 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 19 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_19 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 20 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_20 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 21 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_21 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 22 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_22 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 23 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_23 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 24 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_24 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 25 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_25
sleep 0.5
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 26 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_26 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 27 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_27 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 28 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_28 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 29 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_29 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 30 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_30 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 31 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_31 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 32 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_32 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 33 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_33 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 34 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_34 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 35 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_35 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 36 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_36 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 37 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_37 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 38 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_38 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 39 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_39 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 40 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_40 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 41 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_41 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 42 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_42 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 43 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_43 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 44 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_44 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 45 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_45 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 46 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_46 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 47 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_47 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 48 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_48 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 49 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_49 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 50 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_50
sleep 0.5
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 51 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_51 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 52 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_52 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 53 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_53 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 54 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_54 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 55 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_55 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 56 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_56 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 57 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_57 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 58 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_58 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 59 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_59 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 60 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_60 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 61 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_61 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 62 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_62 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 63 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_63 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 64 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_64 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 65 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_65 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 66 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_66 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 67 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_67 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 68 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_68 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 69 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_69 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 70 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_70 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 71 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_71 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 72 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_72 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 73 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_73 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 74 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_74 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 75 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_75
sleep 0.5
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 76 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_76 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 77 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_77 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 78 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_78 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 79 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_79 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 80 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_80 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 81 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_81 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 82 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_82 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 83 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_83 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 84 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_84 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 85 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_85 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 86 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_86 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 87 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_87 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 88 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_88 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 89 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_89 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 90 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_90 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 91 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_91 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 92 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_92 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 93 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_93 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 94 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_94 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 95 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_95 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 96 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_96 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 97 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_97 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 98 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_98 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 99 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_99 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 100 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_100
sleep 0.5
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 101 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_101 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 102 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_102 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 103 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_103 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 104 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_104 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 105 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_105 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 106 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_106 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 107 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_107 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 108 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_108 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 109 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_109 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 110 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_110 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 111 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_111 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 112 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_112 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 113 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_113 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 114 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_114 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 115 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_115 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 116 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_116 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 117 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_117 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 118 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_118 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 119 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_119 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 120 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_120 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 121 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_121 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 122 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_122 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 123 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_123 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 124 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_124 & 
./shuffle_sweep_script_nocut.pl ./ ./shuffled_sweep_files/ ./valid_file.txt 125 ./ensembl_gene_coords_v99.txt all_ranks_ihs 1000kb 10 2000 && gzip -f ./shuffled_sweep_files/*_125
sleep 0.5
